config/routes.rb
Rails.application.routes.draw do

  get 'password_reset/new'

  post 'password_reset/create'

  get 'password_reset/edit'

  patch 'password_reset/update'

  get 'passwords',to: 'passwords#edit'

  patch 'passwords', to:'passwords#update'

  get 'about', to: "about#index"

  get 'sign_up', to: "registrations#new"
  post 'sign_up', to: "registrations#create"

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create' 

  delete "logout", to: "sessions#destroy"

  root to: 'main#index'

end

app/models/current.rb
class Current 
  include Mongoid::Document
  include ActiveModel::SecurePassword
  attr_accessor :user
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  field :email, type: String
  validates :email, presence: true , uniqueness: true   
  field :password_digest, type: String
  has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_current_user
  
  def set_current_user
    # debugger
    if session[:user_id]
      @current_user = User.find_by(id: session[:user_id])  
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be logged in" if @current_user.nil?
  end

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user 
      Password.with(user: @user).reset.deliver_now
    end
    redirect_to root_path, notice: "Email is sent. Check your inbox!"
  end

  def edit
  end

  def update
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    # debugger
    if @current_user.update_attributes(password_params)
      redirect_to root_path, notice: "Password updated successfully!"
    else
      render :edit
    end
  end

  private 
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(set_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to root_path
      flash[:success] = "Account Created Successfully !"
    else
      render :new
    end
  end

  private

    def set_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
  def new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    # debugger
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id.to_s
      redirect_to root_path, notice: "logged in"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
    # render plain: "test #{ User.find_by(email: params[:user][:email]) }"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path,  alert: "logged out"
  end

  # private

  #   def set_user
  #     @user = User.find_by(email: params[:email])
  #   end

  #   def set_params
  #     params.require(:user).permit(:email, :password)
  #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/about/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>About</h1>
  <p>This is about page</p>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>  
</head>
<body>

<%= render 'shared/header' %>
<div class="container">
  <%= render 'shared/alerts' %>
  <%= yield %>
</div>
</body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>Welcome to the App</h1>
</div>

app/views/password/reset.html.erb
<h1>Password#reset</h1>

<p>
  <%= @greeting %>, find me in app/views/password/reset.html.erb
</p>

app/views/password/reset.text.erb
Password#reset

<%= @greeting %>, find me in app/views/password/reset.text.erb

app/views/password_reset/edit.html.erb
<div class="container mt-3">
  <div class="row justify-content-md-center">
    <div class="col-md-auto border p-5">
    <h1 class="mb-3">Forgot Password</h1> 
      <%= form_for :user, url: password_reset_update_path do |f| %>
        <div class="mb-3">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="">
          <%= f.submit "Send Password Reset Link", class: "btn btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/password_reset/new.html.erb
<h1>PasswordReset#new</h1>
<p>Find me in app/views/password_reset/new.html.erb</p>

app/views/shared/_alerts.html.erb
<% if flash[:notice] %>
<div class= "alert alert-info alert-dismissible" >
  <%= flash[:notice]  %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

<% if flash[:alert] %>
<div class= "alert alert-danger alert-dismissible" >
  <%= flash[:alert]  %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

<% if flash[:success] %>
<div class= "alert alert-success alert-dismissible" >
  <%= flash[:success]  %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "App", root_url, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_url, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_url, class: "nav-link" %>
        </li>
        <li class="nav-item">
        </li>
      </ul>

      <ul class="navbar-nav">
        <% if @current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Change Password", passwords_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log Out", logout_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>